"""add cascade on delete

Revision ID: 375b9c309db9
Revises: e10be277dc49
Create Date: 2025-12-20 21:05:40.408542

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "375b9c309db9"
down_revision: Union[str, Sequence[str], None] = "e10be277dc49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("comments_parent_id_fkey"), "comments", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("comments_user_id_fkey"), "comments", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("comments_movie_id_fkey"), "comments", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "comments", "movies", ["movie_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "comments", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "comments", "comments", ["parent_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("comments_likes_comment_id_fkey"),
        "comments_likes",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("comments_likes_user_id_fkey"),
        "comments_likes",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "comments_likes",
        "comments",
        ["comment_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "comments_likes",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("movie_directors_director_id_fkey"),
        "movie_directors",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("movie_directors_movie_id_fkey"),
        "movie_directors",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "movie_directors",
        "directors",
        ["director_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "movie_directors",
        "movies",
        ["movie_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("movie_genres_genre_id_fkey"), "movie_genres", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movie_genres_movie_id_fkey"), "movie_genres", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "movie_genres",
        "movies",
        ["movie_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "movie_genres",
        "genres",
        ["genre_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("movie_stars_movie_id_fkey"), "movie_stars", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movie_stars_star_id_fkey"), "movie_stars", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "movie_stars", "movies", ["movie_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "movie_stars", "stars", ["star_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("movies_likes_movie_id_fkey"), "movies_likes", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("movies_likes_user_id_fkey"), "movies_likes", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "movies_likes", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "movies_likes",
        "movies",
        ["movie_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("ratings_movie_id_fkey"), "ratings", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("ratings_user_id_fkey"), "ratings", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "ratings", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "ratings", "movies", ["movie_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("user_favorites_movie_id_fkey"),
        "user_favorites",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("user_favorites_user_id_fkey"),
        "user_favorites",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "user_favorites",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_favorites",
        "movies",
        ["movie_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("user_profiles_user_id_fkey"), "user_profiles", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "user_profiles", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("users_group_id_fkey"), "users", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "users", "user_groups", ["group_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("users_group_id_fkey"),
        "users",
        "user_groups",
        ["group_id"],
        ["id"],
    )
    op.drop_constraint(None, "user_profiles", type_="foreignkey")
    op.create_foreign_key(
        op.f("user_profiles_user_id_fkey"),
        "user_profiles",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(None, "user_favorites", type_="foreignkey")
    op.drop_constraint(None, "user_favorites", type_="foreignkey")
    op.create_foreign_key(
        op.f("user_favorites_user_id_fkey"),
        "user_favorites",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("user_favorites_movie_id_fkey"),
        "user_favorites",
        "movies",
        ["movie_id"],
        ["id"],
    )
    op.drop_constraint(None, "ratings", type_="foreignkey")
    op.drop_constraint(None, "ratings", type_="foreignkey")
    op.create_foreign_key(
        op.f("ratings_user_id_fkey"), "ratings", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("ratings_movie_id_fkey"),
        "ratings",
        "movies",
        ["movie_id"],
        ["id"],
    )
    op.drop_constraint(None, "movies_likes", type_="foreignkey")
    op.drop_constraint(None, "movies_likes", type_="foreignkey")
    op.create_foreign_key(
        op.f("movies_likes_user_id_fkey"),
        "movies_likes",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("movies_likes_movie_id_fkey"),
        "movies_likes",
        "movies",
        ["movie_id"],
        ["id"],
    )
    op.drop_constraint(None, "movie_stars", type_="foreignkey")
    op.drop_constraint(None, "movie_stars", type_="foreignkey")
    op.create_foreign_key(
        op.f("movie_stars_star_id_fkey"),
        "movie_stars",
        "stars",
        ["star_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("movie_stars_movie_id_fkey"),
        "movie_stars",
        "movies",
        ["movie_id"],
        ["id"],
    )
    op.drop_constraint(None, "movie_genres", type_="foreignkey")
    op.drop_constraint(None, "movie_genres", type_="foreignkey")
    op.create_foreign_key(
        op.f("movie_genres_movie_id_fkey"),
        "movie_genres",
        "movies",
        ["movie_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("movie_genres_genre_id_fkey"),
        "movie_genres",
        "genres",
        ["genre_id"],
        ["id"],
    )
    op.drop_constraint(None, "movie_directors", type_="foreignkey")
    op.drop_constraint(None, "movie_directors", type_="foreignkey")
    op.create_foreign_key(
        op.f("movie_directors_movie_id_fkey"),
        "movie_directors",
        "movies",
        ["movie_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("movie_directors_director_id_fkey"),
        "movie_directors",
        "directors",
        ["director_id"],
        ["id"],
    )
    op.drop_constraint(None, "comments_likes", type_="foreignkey")
    op.drop_constraint(None, "comments_likes", type_="foreignkey")
    op.create_foreign_key(
        op.f("comments_likes_user_id_fkey"),
        "comments_likes",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("comments_likes_comment_id_fkey"),
        "comments_likes",
        "comments",
        ["comment_id"],
        ["id"],
    )
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.create_foreign_key(
        op.f("comments_movie_id_fkey"),
        "comments",
        "movies",
        ["movie_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("comments_user_id_fkey"), "comments", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("comments_parent_id_fkey"),
        "comments",
        "comments",
        ["parent_id"],
        ["id"],
    )
    # ### end Alembic commands ###
